spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/how2java?characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/malf/mapper/*.xml
  type-aliases-package: com.malf.pojo
server:
  context-path: /shiro