spring:
  application:
    name: config-server
  cloud:
    config:
      # label 表示分支
      label: master
      server:
        git:
          # uri 表示 git 地址
          uri: https://github.com/lingfeng23/how2jStudy
          # searchPaths 表示目录
          searchPaths: /tree/master/distributed/parent
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
