eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-zuul-service
# 所有的访问 /api-codes/ 的请求，都会自动转到 INDEX-CODES-SERVICE 去，
# 而 INDEX-CODES-SERVICE 有3个，就会在这3个之间来回切换。
zuul:
  routes:
    api-a:
      path: /api-codes/**
      serviceId: INDEX-CODES-SERVICE
