spring:
  # database
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/how2java?characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    # 显示 hibernate运行的 sql 语句
    show-sql: true

  # thymeleaf
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  # 设置上传文件大小，默认1M
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
server:
  context-path: /pro_tmall