server:
  servlet:
      context-path: /

#thymeleaf 配置
spring:
  thymeleaf:
    mode: HTM5
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 缓存设置为false, 这样修改之后马上生效，便于调试
    cache: false


